### ISSUE TITLE
Values prefilled in code not shown in form until model is persisted

### ISSUE THREAD

**Issue by SchizoDuckie** [Distilleries/FormBuilder#3]
Hi first of all, thanks for a great lib :+1: 

I'm trying to get some more usability for some forms by pre-filling some data on a new entity:

```php
 public function invoiceForCustomer($customer_id, FormBuilder $formBuilder) {
        $member = Member::findOrNew($customer_id)->with('address')->get()->first();

        $model = new Invoice();
        $model->member()->associate($member);
        $model->address()->associate($member->address);
        $model->invoicenumber = '12345';
        // $model->save();
        $form = $formBuilder::create($this->formType, [
            'method' => 'POST',
            'url' => route("{$this->routeNamespace}.save"),
            'model' => $model
        ]);

        return view("{$this->viewNamespace}.show", [
            'form' => $form,
            'routeNamespace' => $this->routeNamespace,
            'categoryTitle' => $this->categoryTitle,
            'categoryIconClass' => $this->categoryIconClass,
            'listTitle' => $this->listTitle,
            'listLinkTitle' => $this->listLinkTitle,
            'editTitle' => $this->editTitle,
            'editLinkTitle' => $this->editLinkTitle
        ]);
}
```

However, the form does not show the contents until the model is persisted:

without save
![image](https://cloud.githubusercontent.com/assets/111710/12662495/19d5dd8c-c621-11e5-887b-25f1ca03616a.png)

with save:
![image](https://cloud.githubusercontent.com/assets/111710/12662536/56019ee0-c621-11e5-9ba3-efa976c5f721.png)

I tought it may had been a problem with the kris/laravel-form-builder dependency, but was able to verify that an upgrade to the latest version did not change anything.

Do you have any tips on where to start patching this?
(i'm willing to send pull requests!)

**Comment by mfrancois** [comment]
Hi thanks you so much.
Can you past you form code please?

I think that come from you use relationships from laravel. When you have the you need to define the default_value like that :
```php
$this->add('address', 'address_picker',[
                'validation' => 'required',
                'label' => trans('forms.address'),
                'default_value' => $this->model->address
]);
```

On this example I give the relation directly. If you need tho have more complexe part I preconise to use sub form :

```php
       $this->add('profile', 'form', [
                'label' => trans('forms.profile'),
                'icon'  => 'globe',
                'class' => \FormBuilder::create('\App\Forms\ProfileForm', [
                    'model'                     => $this->model->profile
                ])
            ])
```

I hope that help you.

Cheers,
Maxime

**Comment by SchizoDuckie** [comment]
Thanks for this! Isnt it a bit weird api-wise that you also have to use
default_value for non-relations? (See the invoicenumber field)  I'll show
you a form example tonight but it's really simple. Would you be interested
in a PR for my select2 implementation too?

Op 29 jan. 2016 10:42 schreef "Maxime François" <notifications@github.com>:
>
> Hi thanks you so much.
> Can you past you form code please?
>
> I think that come from you use relationships from laravel. When you have
the you need to define the default_value like that :
>
> $this->add('address', 'address_picker',[
>                 'validation' => 'required',
>                 'label' => trans('forms.address'),
>                 'default_value' => $this->model->address
> ]);
>
> On this example I give the relation directly. If you need tho have more
complexe part I preconise to use sub form :
>
>        $this->add('profile', 'form', [
>                 'label' => trans('forms.profile'),
>                 'icon'  => 'globe',
>                 'class' => \FormBuilder::create('\App\Forms\ProfileForm',
[

**Comment by SchizoDuckie** [comment]
Thanks a lot :+1: I can see the flexibility of the default_value field now.

My form now looks like this and it's working like a charm

```php
<?php

namespace App\Forms;

use App\Models\BreedshipType;
use Distilleries\FormBuilder\FormValidator;
use App\Models\Customer;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\DB;



class InvoiceForm extends FormValidator
{
    public function buildForm()
    {
        $this
            ->add('id', 'hidden')
            ->add('invoicenumber', 'text', [
                'label' => 'Factuurnummer',
                'validation' => 'required',
                'default_value' => $this->model->invoicenumber
            ])
            ->add('invoicedate', 'date', [
                'label' => 'Factuurdatum',
                'default_value' => $this->model->invoicedate
            ])
            ->add('is_paid', 'choice',  [
                'label'=> 'Betaalstatus',
                'expanded' => true,
                'choices' => [
                    '0'=>'Openstaand',
                    '1'=>'Betaald'
                ],
                'default_value' => $this->model->is_paid
            ])
            ->add('reminded', 'date',  [
                'label'=> 'Herinnering verstuurd',
                'default_value' => ''
            ])
            ->add('member_id', 'choice_ajax_add', [
                'label'      => 'Lid',
                'action'     => route('member.ajaxsearch'),
                'default_value' => $this->model->member_id,
                'validation' => 'required',
                'minimumInputLength' => 0,
                'add' => true,
                'create_route' => route('member.create'),
                'edit_route' => route('member.edit', (($this->model) ? $this->model->member_id : null)),
                'formatter'  => [
                    'id'      => 'id',
                    'libelle' => 'firstname, lastname',
                ],
            ])

            ->add('address_id', 'choice_ajax_add', [
                'label'      => 'Adres',
                'action'     => route('address.ajaxsearch'),
                'default_value' => $this->model->address_id,
                'validation' => 'required',
                'minimumInputLength' => 0,
                'add' => true,
                'create_route' => route('address.create'),
                'edit_route' => route('address.edit', (($this->model) ? $this->model->address_id : null)),
                'formatter'  => [
                    'id'      => 'id',
                    'libelle' => 'street,zipcode,city',
                ],
            ])
            ->add('submit', 'submit', ['label' => 'Save', 'attr' => ['class' => 'btn'],], false, true);
    }
}
```

**Comment by mfrancois** [comment]
Cool. 

If you have any issu come back. 
Have a look on choice ajax is select2 implementation if you have an other one create a pull request with the testing and I will merge it.

Regards,
Maxime
